name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove old Flutter
        run: sudo rm -rf /opt/hostedtoolcache/flutter

      - name: Install Flutter 3.27.3 manually
        run: |
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.27.3-stable.tar.xz
          tar xf flutter_linux_3.27.3-stable.tar.xz
          export PATH="$PWD/flutter/bin:$PATH"
          flutter --version
          dart --version

      - name: Install dependencies
        run: flutter pub get

      - name: Generate JSON serialization files
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: flutter build apk --release

      - name: Build AppBundle (AAB)
        run: flutter build appbundle --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-build
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
